# Generated by Django 4.2.1 on 2026-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starship',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='starship',
            index=models.Index(fields=['-time_create'], name='mandalore_s_time_cr_a8b69d_idx'),
        ),
    ]
