# Generated by Django 4.2.1 on 2026-03-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandalore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='starship',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mandalore.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='starship',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starship', to='mandalore.shippassport'),
        ),
        migrations.AddField(
            model_name='starship',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mandalore.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='starship',
            index=models.Index(fields=['-time_create'], name='mandalore_s_time_cr_a8b69d_idx'),
        ),
    ]
