# Generated by Django 4.2.1 on 2026-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0002_alter_starship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
