# Generated by Django 4.2.1 on 2026-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starship',
            options={'permissions': [('can_publish_starship', 'Может публиковать статьи')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveIndex(
            model_name='starship',
            name='mandalore_s_time_cr_a8b69d_idx',
        ),
    ]
