# Generated by Django 4.2.1 on 2026-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0003_starship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
