# Generated by Django 4.2.1 on 2026-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0004_alter_starship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
