# Generated by Django 4.2.1 on 2026-02-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0006_category_starship_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mandalore.category'),
        ),
    ]
