# Generated by Django 4.2.1 on 2026-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0007_alter_starship_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='starship',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mandalore.tagpost'),
        ),
    ]
