# Generated by Django 4.2.1 on 2026-02-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0008_tagpost_starship_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='starship',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starship', to='mandalore.shippassport'),
        ),
    ]
