# Generated by Django 4.2.1 on 2026-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0009_shippassport_starship_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippassport',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
