# Generated by Django 4.2.1 on 2026-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalore', '0011_uploadfiles_alter_starship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
